# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiveDemo
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket',
    'RCTImage',
    'RCTAnimation',
    'RCTNetwork'# needed for debugging
    # Add any other subspecs you want to use in your project
    ]
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
    pod 'BaiduBCECapture', "~> 2.0"
    pod 'BaiduBCEPlayerLSS', "2.0.0"
    pod 'RongCloudIM', "~> 2.8.14"
end
